// Auto-generated by svg-sprite-watcher. Do not edit.
import "svg-sprite-watcher/components/react";
import "svg-sprite-watcher/components/astro";

declare module "svg-sprite-watcher" {
  export type IconName = 
    | "circle";
}
