
// Auto-generated by svg-sprite-watcher. Do not edit.
import "svg-sprite-watcher";

declare module "svg-sprite-watcher" {
  export type IconName = 
    | "arrow-left"
    | "arrow-up"
    | "ca"
    | "cb"
    | "envelope"
    | "facebook"
    | "facebook-official"
    | "instagram"
    | "instagram-official"
    | "left-quote"
    | "play-button"
    | "quote"
    | "right-quote"
    | "vite"
    | "youtube"
    | "youtube-official";

  export const iconNames: readonly IconName[];
  export function isValidIcon(name: string): name is IconName;
}

declare module "svg-sprite-watcher/components/react" {
  import * as React from "react";
  import { IconName } from "svg-sprite-watcher";
  export type IconProps = React.SVGProps<SVGSVGElement> & {
    name: IconName;
    title?: string;
    size?: number | string;
    color?: string;
    spriteUrl?: string;
  };
  export const Icon: React.FunctionComponent<IconProps>;
}

declare module "svg-sprite-watcher/components/astro" {
  export interface Props {
    name: import("svg-sprite-watcher").IconName;
    size?: number | string;
    color?: string;
    title?: string;
    spriteUrl?: string;
    [key: string]: any;
  }
  export default function Icon(props: Props): any;
}
