\
// Auto-generated by svg-sprite-generator. Do not edit.
import "svg-sprite-generator";

declare module "svg-sprite-generator" {
  export type IconName = 
    | "arrow-left"\n    | "arrow-right"\n    | "arrow-up"\n    | "ca"\n    | "cb"\n    | "envelope"\n    | "facebook"\n    | "facebook-official"\n    | "instagram"\n    | "instagram-official"\n    | "left-quote"\n    | "play-button"\n    | "quote"\n    | "right-quote"\n    | "vite"\n    | "youtube"\n    | "youtube-official";

  export const iconNames: readonly IconName[];
  export function isValidIcon(name: string): name is IconName;
}
