// Auto-generated by svg-sprite-generator. Do not edit.
import "svg-sprite-watcher";

declare module "svg-sprite-watcher" {
  export type IconName = 
    | "arrow-left"
    | "arrow-up"
    | "ca"
    | "cb"
    | "envelope"
    | "facebook"
    | "facebook-official"
    | "instagram"
    | "instagram-official"
    | "left-quote"
    | "play-button"
    | "quote"
    | "right-quote"
    | "vite"
    | "youtube"
    | "youtube-official";
}
