// Auto-generated by svg-sprite. Do not edit.
import type { IconName } from "../sprite.gen";
import type { CSSProperties, FC } from "react";

export interface IconProps {
  name: IconName;
  className?: string;
  style?: CSSProperties;
  spriteUrl?: string;
}

export const Icon: FC<IconProps> = ({
  name,
  className,
  style,
  spriteUrl = "/sprite.svg",
}) => {
  return (
    <svg className={className} style={style}>
      <use href={`${spriteUrl}#${name}`} />
    </svg>
  );
};
