import fs from "fs";
import path from "path";
import { SpriteConfig } from "../config";
import { logger } from "../logger";
import { ensureDir, resolvePath } from "../utils/paths";

export async function generateAstroComponent(config: SpriteConfig) {
  const components = config.components as any;
  const astroOutput = Array.isArray(components)
    ? "src/components/Icon.astro"
    : components?.astro || "src/components/Icon.astro";

  const componentPath = resolvePath(astroOutput);
  ensureDir(path.dirname(componentPath));

  // Determine relative path to types file
  let typesImportPath = "../sprite.gen";
  if (config.typesOutput) {
    const typesPath = resolvePath(config.typesOutput);
    typesImportPath = path
      .relative(path.dirname(componentPath), typesPath)
      .replace(/\\/g, "/")
      .replace(/\.ts$/, "");

    if (!typesImportPath.startsWith(".")) {
      typesImportPath = `./${typesImportPath}`;
    }
  }

  const output = `\
---
// Auto-generated by svg-sprite. Do not edit.
import type { IconName } from "${typesImportPath}";

export interface Props extends astroHTML.JSX.SVGAttributes {
  name: IconName;
  spriteUrl?: string;
}

const { name, spriteUrl = "${config.spriteUrl || "/sprite.svg"}", ...props } = Astro.props;
---

<svg {...props}>
  <use href={\`\${spriteUrl}#\${name}\`} />
</svg>
`;

  fs.writeFileSync(componentPath, output, "utf-8");
  logger.success(`Generated ${astroOutput}`);
}
