import fs from "fs";
import path from "path";
import { SpriteConfig } from "../config";
import { logger } from "../logger";
import { resolvePath } from "../utils/paths";

/**
 * Generate global types and runtime variables for the sprite
 * @param config
 * @returns Promise<void>
 *
 */
export async function generateTypes(config: SpriteConfig) {
  if (!config.typesOutput) {
    logger.warn(`No types output path specified`);
    return;
  }

  const outputPath = resolvePath(config.output);
  const typesPath = resolvePath(config.typesOutput);

  try {
    const sprite = fs.readFileSync(outputPath, "utf-8");

    // Extract all <symbol id="..."> tags
    const iconNames = [...sprite.matchAll(/id="([^"]+)"/g)]
      .map((m) => m[1])
      .sort();

    const dtsOutput = `\\
// Auto-generated by svg-sprite-generator. Do not edit.
import "svg-sprite-generator";

declare module "svg-sprite-generator" {
  export type IconName = 
${iconNames.length > 0 ? iconNames.map((name) => `    | "${name}"`).join("\n") : `    string`};

  export const iconNames: readonly IconName[];
  export function isValidIcon(name: string): name is IconName;
}

declare module "svg-sprite-generator/components/react" {
  import * as React from "react";
  import { IconName } from "svg-sprite-generator";
  export type IconProps = React.SVGProps<SVGSVGElement> & {
    name: IconName;
    title?: string;
    size?: number | string;
    color?: string;
    spriteUrl?: string;
  };
  export const Icon: React.FunctionComponent<IconProps>;
}

declare module "svg-sprite-generator/components/astro" {
  export interface Props {
    name: import("svg-sprite-generator").IconName;
    size?: number | string;
    color?: string;
    title?: string;
    spriteUrl?: string;
    [key: string]: any;
  }
  export default function Icon(props: Props): any;
}
`;

    fs.writeFileSync(typesPath, dtsOutput, "utf-8");
    logger.success(`Generated definitions ${path.basename(typesPath)}`);
  } catch (err: any) {
    logger.error(`Failed to generate types: ${err.message}`);
  }
}
