import fs from "fs";
import path from "path";
import { logger } from "../logger";
import { resolvePath } from "../utils/paths";
import { SpriteConfig } from "../types/config";

/**
 * Generate global types and runtime variables for the sprite
 * @param config
 * @returns Promise<void>
 *
 */
export async function generateTypes(config: SpriteConfig) {
  if (!config.typesOutput) {
    logger.warn(`No types output path specified`);
    return;
  }

  const outputPath = resolvePath(config.output);
  const typesPath = resolvePath(config.typesOutput);

  try {
    const sprite = fs.readFileSync(outputPath, "utf-8");

    // Extract all <symbol id="..."> tags
    const iconNames = [...sprite.matchAll(/id="([^"]+)"/g)]
      .map((m) => m[1])
      .toSorted();

    const dtsOutput = `\
// Auto-generated by svg-sprite-watcher. Do not edit.
import "svg-sprite-watcher/components/react";
import "svg-sprite-watcher/components/astro";

declare module "svg-sprite-watcher" {
  export type IconName = 
${iconNames.length > 0 ? iconNames.map((name) => `    | "${name}"`).join("\n") : `    string`};
}
`;

    fs.writeFileSync(typesPath, dtsOutput, "utf-8");
    logger.success(`Generated definitions ${path.basename(typesPath)}`);
  } catch (err: any) {
    logger.error(`Failed to generate types: ${err.message}`);
  }
}
