    // Auto-generated by svg-sprite. Do not edit.
    // Re-run generator to update.

    export type IconName = 
      | "home";

    export const ICON_NAMES = [
      "home",
    ] as const;

    export function isValidIcon(name: string): name is IconName {
      return ICON_NAMES.includes(name as IconName);
    }
    