import fs from "fs";
import path from "path";
import { SpriteConfig } from "../config";
import { logger } from "../logger";
import { ensureDir, resolvePath } from "../utils/paths";

export async function generateReactComponent(config: SpriteConfig) {
  const components = config.components as any;
  const reactOutput = Array.isArray(components)
    ? "src/components/Icon.tsx"
    : components?.react || "src/components/Icon.tsx";

  const componentPath = resolvePath(reactOutput);
  ensureDir(path.dirname(componentPath));

  // Determine relative path to types file
  let typesImportPath = "../sprite.gen";
  if (config.typesOutput) {
    const typesPath = resolvePath(config.typesOutput);
    typesImportPath = path
      .relative(path.dirname(componentPath), typesPath)
      .replace(/\\/g, "/")
      .replace(/\.ts$/, "");

    if (!typesImportPath.startsWith(".")) {
      typesImportPath = `./${typesImportPath}`;
    }
  }

  const output = `\
// Auto-generated by svg-sprite. Do not edit.
import type { IconName } from "${typesImportPath}";
import type { CSSProperties, FC } from "react";

export interface IconProps {
  name: IconName;
  className?: string;
  style?: CSSProperties;
  spriteUrl?: string;
}

export const Icon: FC<IconProps> = ({
  name,
  className,
  style,
  spriteUrl = "${config.spriteUrl || "/sprite.svg"}",
}) => {
  return (
    <svg className={className} style={style}>
      <use href={\`\${spriteUrl}#\${name}\`} />
    </svg>
  );
};
`;

  fs.writeFileSync(componentPath, output, "utf-8");
  logger.success(`Generated ${reactOutput}`);
}
