import fs from "fs";
import { SpriteConfig } from "../config";
import { logger } from "../logger";
import { resolvePath } from "../utils/paths";

/**
 * Generate types for the sprite
 * @param config
 * @returns Promise<void>
 *
 */
export async function generateTypes(config: SpriteConfig) {
  if (!config.typesOutput) {
    logger.warn(`No types output path specified`);
    return;
  }

  const outputPath = resolvePath(config.output);
  const typesPath = resolvePath(config.typesOutput);

  try {
    const sprite = fs.readFileSync(outputPath, "utf-8");

    // Extract all <symbol id="..."> tags
    const iconNames = [...sprite.matchAll(/id="([^"]+)"/g)]
      .map((m) => m[1])
      .sort();

    const output = `\
    // Auto-generated by svg-sprite. Do not edit.
    // Re-run generator to update.

    export type IconName = 
    ${iconNames.map((name) => `  | "${name}"`).join("\n")};

    export const ICON_NAMES = [
    ${iconNames.map((name) => `  "${name}",`).join("\n")}
    ] as const;

    export function isValidIcon(name: string): name is IconName {
      return ICON_NAMES.includes(name as IconName);
    }
    `;

    fs.writeFileSync(typesPath, output, "utf-8");
    logger.success(`Generated ${config.typesOutput}`);
  } catch (err: any) {
    logger.error(`Failed to generate types: ${err.message}`);
  }
}
