import { spawn, type ChildProcess } from "child_process";
import path from "path";
import fs from "fs";
import { loadConfig } from "../config";
import { resolvePath } from "../utils/paths";

type AstroSetupContext = {
  injectTypes?: (args: { filename: string; content: string }) => void;
};

function isAstroSetupContext(value: unknown): value is AstroSetupContext {
  return typeof value === "object" && value !== null;
}

export default function astroPluginSvgSprite() {
  let child: ChildProcess | null = null;

  return {
    name: "astro-plugin-svg-sprite",
    hooks: {
      "astro:config:setup": async (setupContext: unknown) => {
        const injectTypes = isAstroSetupContext(setupContext)
          ? setupContext.injectTypes
          : undefined;

        if (injectTypes) {
          const config = await loadConfig();
          if (config) {
            const outputPath = resolvePath(config.output);
            let iconNames: string[] = [];

            if (fs.existsSync(outputPath)) {
              const sprite = fs.readFileSync(outputPath, "utf-8");
              iconNames = [...sprite.matchAll(/id="([^"]+)"/g)]
                .map((m) => m[1])
                .toSorted();
            }

            const dtsOutput = `// Auto-generated by svg-sprite-watcher. Do not edit.
import "svg-sprite-watcher";

declare module "svg-sprite-watcher" {
  export type IconName = 
${iconNames.length > 0 ? iconNames.map((name) => `    | "${name}"`).join("\n") : `    string`};

  export const iconNames: readonly IconName[];
  export function isValidIcon(name: string): name is IconName;
}

declare module "svg-sprite-watcher/components/react" {
  import * as React from "react";
  import { IconName } from "svg-sprite-watcher";
  export type IconProps = React.SVGProps<SVGSVGElement> & {
    name: IconName;
    title?: string;
    size?: number | string;
    color?: string;
    spriteUrl?: string;
  };
  export const Icon: React.FunctionComponent<IconProps>;
}

declare module "svg-sprite-watcher/components/astro" {
  export interface Props {
    name: import("svg-sprite-watcher").IconName;
    size?: number | string;
    color?: string;
    title?: string;
    spriteUrl?: string;
    [key: string]: any;
  }
  export default function Icon(props: Props): any;
}
`;
            injectTypes({
              filename: "types.d.ts",
              content: dtsOutput,
            });
          }
        }
      },
      "astro:server:setup": () => {
        if (child) return;
        const cliPath = path.resolve(
          process.cwd(),
          "node_modules/.bin/svg-sprite-watcher",
        );
        child = spawn(cliPath, ["--watch", "--no-types"], {
          stdio: "inherit",
          shell: true,
        });
      },
      "astro:server:done": () => {
        if (child) child.kill();
      },
      "astro:build:start": () => {
        if (!child) {
          const cliPath = path.resolve(
            process.cwd(),
            "node_modules/.bin/svg-sprite-watcher",
          );
          spawn(cliPath, ["--no-types"], {
            stdio: "inherit",
            shell: true,
          });
        }
      },
    },
  };
}
